version: "3.9"

services:
  microservice:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice
    expose:
      - "8000"
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=microservice
      - SERVER_PORT=8080
      - SPRING_ZIPKIN_BASE_URL=http://host.docker.internal:9411
      - SPRING_R2DBC_URL=r2dbc:postgresql://host.docker.internal:5432/bank_accounts
      - SPRING_FLYWAY_URL=jdbc:postgresql://host.docker.internal:5432/bank_accounts
      - SPRING_REDIS_HOST=host.docker.internal
      - JAVA_OPTS="-XX:+UseG1GC -XX:MaxRAMPercentage=75"
    depends_on:
      - microservices_postgresql
      - prometheus
      - grafana
      - zipkin
      - node_exporter
    networks: [ "microservices" ]

  microservices_postgresql:
    image: postgres:latest
    container_name: microservices_postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_accounts
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
      - ./docker_data/microservices_pgdata:/var/lib/postgresql/data
    networks: [ "microservices" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [ "microservices" ]

  node_exporter:
    container_name: microservices_node_exporter
    restart: always
    image: prom/node-exporter
    ports:
      - '9101:9100'
    networks: [ "microservices" ]

  grafana:
    container_name: microservices_grafana
    restart: always
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks: [ "microservices" ]

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    container_name: microservices_zipkin
    ports:
      - "9411:9411"
    networks: [ "microservices" ]

networks:
  microservices:
    name: microservices